version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/trstringer/go-systemd-time
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: golint -set_exit_status ./...
      - run: go test -v ./...
